basePath: /api/v1
info:
  contact: {}
  description: This is a Social Nyetwork server.
  license:
    name: WTFPL 2.0
    url: http://www.wtfpl.net/txt/copying/
  title: Social Nyetwork Swagger
  version: "1.0"
paths: {}
swagger: "2.0"
